version: 2.1

# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: circleci/postgres:alpine
    steps:
      - checkout
      - run: apk add docker-cli
      - run: docker build -f Dockerfile -t your_project:$CIRCLE_BRANCH .
      - run: mkdir -p docker-cache
      - run: docker save -o docker-cache/image.zip your_project:$CIRCLE_BRANCH
  test:
    docker:
      - image: circleci/postgres:alpine
    steps:
      - checkout
      - run: echo "HERE"
  deploy:
    docker:
      - image: circleci/postgres:alpine
    steps:
      - checkout
      - run: scp docker-cache/image.zip acs@app.smartbooks365.com:/home/acs

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
      - hold:
          type: approval
          requires:
            - build
            - test
      - deploy:
          requires:
            - hold
